config/routes.rb
Feedback::Engine.routes.draw do
  root to: 'feedback_infos#index'
  resources :feedback_infos
end

app/models/feedback/feedback_info.rb
module Feedback
  class FeedbackInfo 
    include Mongoid::Document
    include Mongoid::Timestamps
    field :title
    field :username
    field :content
    field :current_url
    field :image
    
    validates :title, presence: true
    validates :content, presence: true
  end
end

app/controllers/feedback/application_controller.rb
module Feedback
  class ApplicationController < ActionController::Base
    layout Proc.new { |controller| controller.request.xhr? ? false : 'application' }
  end
end

app/controllers/feedback/feedback_infos_controller.rb
# encoding: utf-8

module Feedback
  class FeedbackInfosController < ApplicationController
    skip_authorization_check
    respond_to :html, :json, :js
    layout "home"

    def index
      @feedback_infos = FeedbackInfo.paginate(:page => params[:page], :per_page => 10)
    end

    def new
      @feedback_info = FeedbackInfo.new
      render :layout => false
    end

    def show
      @feedback_info = FeedbackInfo.find(params[:id]) 
    end

    def create
      @feedback_info = FeedbackInfo.new(params[:feedback_info])
      if (@flag = @feedback_info.save)
        Resque.enqueue(Email,"意见反馈",Email.to_html("send_feedback_info",@feedback_info.attributes),Settings.feedback_receiver)
      end
      render :layout => false
    end
  end
end

app/views/feedback/feedback_infos/_feedback.slim
div id="myModal" class="modal hide fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
  = simple_form_for @feedback_info, html: { class: 'form-horizontal'}, remote: true do |f|
    div class="modal-header"
      button type="button" class="close" data-dismiss="modal" aria-hidden="true" x
      h3 id="myModalLabel" 产品问题反馈
    div class="modal-body"
      div class="alert hide"
      fieldset
        label 标题
        = f.input_field :title
        label 内容
        = f.text_area :content,rows:"3", style:"max-width:516px;min-width:516px;min-height:116px"
        = f.input_field :username,:type=>"hidden", :value => session[:login]
        = f.input_field :current_url, :type => "hidden"
        = f.input_field :image, :type => "hidden"
        label 页面截图预览
        div id="image-show" style="width:516px;height:120px;"
          img id="image" style="height:120px;"
    div class="modal-footer"
      button class="btn" data-dismiss="modal" aria-hidden="true" 关闭
      = f.button :submit ,:value => "提交",class: 'btn btn-primary'

app/views/feedback/feedback_infos/index.slim
div class="row-fluid"
  div class="span9 content"
    - @feedback_infos.each do |feedback_info|
      article class="shadow-box"
        header class="modal-header"
          h2
            = link_to feedback_info.title,feedback_info_path(feedback_info)
        section class="modal-body"
          = feedback_info.content
        footer class="text-left modal-footer"
          i class="icon-time"
          = feedback_info.created_at.to_s(:db)
          i class="separate"
          ||
          i class="icon-user"
          = feedback_info.username
          i class="separate"
          ||
          a href="/blog/create-weixin-api-by-rails.html#comments"
            |6条评论
  div class="span3"

style type="text/css"
  |.shadow-box{box-shadow: 0 0 6px rgba(0,0,0,0.2);margin-top: 20px;margin-left: 20px;border: 1px solid #ccc;border-radius: 4px;background: #fff;}

app/views/feedback/feedback_infos/show.slim
div class="row-fluid"
  div class="span12 content"
    article class="shadow-box"
      header class="modal-header"
        h2
          = @feedback_info.title
        p
          i class="icon-time"
          = @feedback_info.created_at.to_s(:db)
          i class="separate"
          ||
          i class="icon-user"
          = @feedback_info.username
      section class="modal-body"
        = @feedback_info.content
        div
          p 截图预览: 
          = image_tag(@feedback_info.image, :width => '640',:style => 'border: 1px solid #ccc;')
      footer class="text-left modal-footer"
        i class="icon-time"
        = @feedback_info.created_at.to_s(:db)
        i class="separate"
        ||
        i class="icon-user"
        = @feedback_info.username
        i class="separate"
        ||
        a href="#"
          |6条评论

style type="text/css"
  |.shadow-box{box-shadow: 0 0 6px rgba(0,0,0,0.2);margin-top: 20px;margin-left: 20px;margin-right: 20px;border: 1px solid #ccc;border-radius: 4px;background: #fff;}